[build]
  publish = "dist/"
  command = "npm install && npx --no-install elm-tooling install && PATH=$(npm bin):$PATH npm run elm-graphql && npx elm-pages build"
[build.environment]
  ELM_HOME = "$NETLIFY_BUILD_BASE/cache/elm"
  NO_ELM_TOOLING_INSTALL = "1"
